server:
  port: 8008

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 112211
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
      encoding: utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.njxzc.entity
  configuration:
    map-underscore-to-camel-case: true